### ISSUE TITLE
Env variables documentation

### ISSUE THREAD

**Issue by CiaranPearse** [alexbacanu/recommen.do#1]
Fantastic repo and I plan on using it for my own project.

Can you share what the endpoints are for the webhooks etc.

Maybe a gist of the .env file with annotations on where to get/set each key/path.

Specifically the following:
APPWRITE_WEBHOOK_KEY: Need to define an endpoint to set one up
STRIPE_WEBHOOK_KEY: Need to define an endpoint to set one up
RESEND_API_KEY: Is this from stripe or appwrite and where to set up?
OPENAI_API_KEY: Assume this is from openAi? 
NEXT_PUBLIC_APPWRITE_PROJECT & PLASMO_PUBLIC_APPWRITE_PROJECT: Is this a path to the appwrite project or a project name or ID etc?
NEXT_PUBLIC_APPWRITE_ENDPOINT: assume this would be https://cloud.appwrite.io/v1/xxxx-xxxx-xxxx-xxxx? Correct or no?
NEXT_PUBLIC_APPWRITE_URL: not sure about this as the example starts with http://

If you want I'll nicely document everything as I go once I know where to set everything and do a readme PR.

**Comment by alexbacanu** [comment]
Hey, thanks for the interest.
I'm using Appwrite as a backend, however you can achieve this with any other backend:

- `APPWRITE_WEBHOOK_KEY`: _Webhook that calls /api/stripe/customer every time a document in database is created_
- `*_PUBLIC_APPWRITE_PROJECT` and `*_PUBLIC_APPWRITE_ENDPOINT`: _Appwrite Project ID and Appwrite Endpoint for communicating with Appwrite. That would be just https://cloud.appwrite.io/v1. You can get both [here](https://cloud.appwrite.io/)_
- `*_PUBLIC_APPWRITE_URL`: _Path to the homepage (in my case https://www.recommen.do)_
- `STRIPE_WEBHOOK_KEY`: _Webhook that calls api/stripe/webhook everytime a subscription is created/updated/deleted. You can get one [here](https://dashboard.stripe.com/apikeys)_
- `RESEND_API_KEY`: _Key for using Resend in my contact form. You can get one [here](https://resend.com/)_
- `OPENAI_API_KEY`: _Key for using OpenAI in my prompt. You can get one [here](https://platform.openai.com/account/api-keys)_

I just updated the functions I use, you can check them out [here](https://github.com/alexbacanu/recommen.do-functions/tree/main). Let me know if you have any more questions.

**Comment by CiaranPearse** [comment]
Thanks for the response. Really appreciate it.

I looked at the docs for the functions and they make total sense also. Just a quick question or 2 about the DB structure:

In the profiles collection there is a stripeSubscriptionID but a few places in the code (api/stripe/webhooks) there's mentions of other stripe related attributes. What does the full profiles collection look like?

Also in the identifier collection. What's the purpose of this collection?

Thanks again. I'll send you a PM soon outlining what I'm developing

**Comment by alexbacanu** [comment]
All the attributes for database `main` and collection `profile`:

Key			Type, Default Value, Size
userId			string - 128
name			string - 256
email			string - -
credits			integer 10 9999
usage			integer - max
stripeCurrentPeriodEnd	datetime - -
stripeCustomerId	string - 128
stripePriceId		string - 128
stripeStatus		string - 32
stripeStatusLastUpdated	datetime - -
stripeSubscriptionId	string - 128
stripeSubscriptionName	string - 128
markedForDeletion	datetime - -
termsAgreed		datetime - -
history			string[] - 4096
saveHistory		boolean true -

I probably don't use all of them at the moment, and there could be other optimizations.

The identifier collection is just a way to stop abusing the free grant of the 10 credits. Basically just a hashed version of every email created, and when the user deletes and creates a new account, the new account will be granted 0 credits if the hashed version of the email exists already.

**Comment by CiaranPearse** [comment]
Thanks - almost have it working now. I've been documenting along the way so I'll do a readme PR in the coming days.
